/**
 * Session model for opencue (Phase 6).
 *
 * A "session" is a single meeting capture run: the user starts it (often
 * by starting audio capture), opencue collects transcripts and assist
 * suggestions, and the user stops it. Each session is persisted to disk
 * as a single JSON file so it can be reopened, exported, or deleted later.
 *
 * Lives in `src/shared/` so the renderer can render the list without
 * round-tripping the wire types.
 */

import type { AssistSuggestion, TranscriptEntry } from './provider-types.js';

export interface SessionSummary {
  /** Generated by the LLM (recap prompt) — Markdown. May be empty until the user clicks Summarize. */
  body: string;
  /** Provider that produced it, for transparency. */
  providerId: string;
  /** Model identifier when available. */
  model?: string;
  /** ms since epoch when the summary was generated. */
  generatedAt: number;
}

export interface SessionRecord {
  /** Stable identifier — also the on-disk filename. */
  id: string;
  /** Human-friendly title (default 'Untitled session — <date>'). */
  title: string;
  /** Capture-source label at the time the session started. */
  sourceLabel: string | null;
  /** ms since epoch when the session was opened. */
  startedAt: number;
  /** ms since epoch when the session was closed (null = currently in progress). */
  endedAt: number | null;
  transcript: TranscriptEntry[];
  suggestions: AssistSuggestion[];
  summary: SessionSummary | null;
}

/** Lightweight digest returned by the list endpoint. */
export interface SessionListEntry {
  id: string;
  title: string;
  sourceLabel: string | null;
  startedAt: number;
  endedAt: number | null;
  transcriptCount: number;
  suggestionCount: number;
  hasSummary: boolean;
  /** File size on disk in bytes. */
  diskBytes: number;
}

export function isActive(record: SessionRecord): boolean {
  return record.endedAt === null;
}

export function durationMs(record: SessionRecord): number {
  const end = record.endedAt ?? Date.now();
  return Math.max(0, end - record.startedAt);
}

/**
 * Format a session as clean Markdown — clipboard- and Notion-friendly.
 *
 * Pure function so it can be unit-tested without any storage layer.
 */
export function formatSessionMarkdown(record: SessionRecord, now: number = Date.now()): string {
  const lines: string[] = [];
  lines.push(`# ${record.title}`);
  lines.push('');
  lines.push(`- Started: ${formatTimestamp(record.startedAt)}`);
  if (record.endedAt) lines.push(`- Ended: ${formatTimestamp(record.endedAt)}`);
  if (record.sourceLabel) lines.push(`- Source: ${record.sourceLabel}`);
  lines.push(`- Duration: ${formatDuration(durationMs({ ...record, endedAt: record.endedAt ?? now }))}`);
  lines.push('');

  if (record.summary) {
    lines.push('## Summary');
    lines.push('');
    lines.push(record.summary.body.trim());
    lines.push('');
    lines.push(
      `_Generated by ${record.summary.providerId}${
        record.summary.model ? ` (${record.summary.model})` : ''
      } at ${formatTimestamp(record.summary.generatedAt)}._`,
    );
    lines.push('');
  }

  if (record.suggestions.length > 0) {
    lines.push('## Assist suggestions');
    lines.push('');
    for (const sug of record.suggestions) {
      lines.push(`- **${formatTimestamp(sug.triggeredAt)}** — ${sug.text.replace(/\s+/g, ' ').trim()}`);
    }
    lines.push('');
  }

  if (record.transcript.length > 0) {
    lines.push('## Transcript');
    lines.push('');
    for (const entry of record.transcript) {
      lines.push(`- _${formatTimestamp(entry.startedAt)}_ — ${entry.text.trim()}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

function formatTimestamp(ms: number): string {
  const d = new Date(ms);
  // YYYY-MM-DD HH:MM:SS — stable across locales, matches Notion's preferred format.
  const yyyy = d.getFullYear();
  const mm = `${d.getMonth() + 1}`.padStart(2, '0');
  const dd = `${d.getDate()}`.padStart(2, '0');
  const hh = `${d.getHours()}`.padStart(2, '0');
  const mi = `${d.getMinutes()}`.padStart(2, '0');
  const ss = `${d.getSeconds()}`.padStart(2, '0');
  return `${yyyy}-${mm}-${dd} ${hh}:${mi}:${ss}`;
}

function formatDuration(ms: number): string {
  const totalSec = Math.floor(ms / 1000);
  const hours = Math.floor(totalSec / 3600);
  const minutes = Math.floor((totalSec % 3600) / 60);
  const seconds = totalSec % 60;
  if (hours > 0) return `${hours}h ${minutes}m ${seconds}s`;
  if (minutes > 0) return `${minutes}m ${seconds}s`;
  return `${seconds}s`;
}

/** Default title used when the user doesn't provide one. */
export function defaultSessionTitle(startedAt: number): string {
  const d = new Date(startedAt);
  const yyyy = d.getFullYear();
  const mm = `${d.getMonth() + 1}`.padStart(2, '0');
  const dd = `${d.getDate()}`.padStart(2, '0');
  return `Untitled session — ${yyyy}-${mm}-${dd}`;
}
