import { describe, expect, it } from 'vitest';
import { LlmProviderId, SttProviderId } from './provider-types';
import {
  defaultSessionTitle,
  durationMs,
  formatSessionMarkdown,
  isActive,
  type SessionRecord,
} from './session-types';

function sample(over: Partial<SessionRecord> = {}): SessionRecord {
  const base: SessionRecord = {
    id: 's_1',
    title: 'Q3 planning sync',
    sourceLabel: 'Google Meet — Engineering',
    startedAt: Date.UTC(2026, 5, 10, 9, 0, 0),
    endedAt: Date.UTC(2026, 5, 10, 9, 30, 0),
    transcript: [
      {
        id: 1,
        startedAt: Date.UTC(2026, 5, 10, 9, 1, 0),
        completedAt: Date.UTC(2026, 5, 10, 9, 1, 5),
        text: 'we should ship the cloud beta this week',
        providerId: SttProviderId.OpenAIWhisper,
      },
    ],
    suggestions: [
      {
        id: 1,
        triggeredAt: Date.UTC(2026, 5, 10, 9, 2, 0),
        completedAt: Date.UTC(2026, 5, 10, 9, 2, 4),
        text: 'Propose a Friday cutoff with QA in parallel.',
        streaming: false,
        providerId: LlmProviderId.OpenAI,
        ttsAvailable: false,
      },
    ],
    summary: null,
  };
  return { ...base, ...over };
}

describe('isActive / durationMs', () => {
  it('flags in-progress sessions as active', () => {
    expect(isActive(sample({ endedAt: null }))).toBe(true);
    expect(isActive(sample({ endedAt: 1 }))).toBe(false);
  });

  it('uses now for durationMs when the session is still open', () => {
    const startedAt = Date.now() - 2_000;
    const ms = durationMs(sample({ startedAt, endedAt: null }));
    expect(ms).toBeGreaterThanOrEqual(2_000);
  });

  it('returns 0 for a session with an inverted time range', () => {
    const ms = durationMs(sample({ startedAt: 1_000, endedAt: 500 }));
    expect(ms).toBe(0);
  });
});

describe('defaultSessionTitle', () => {
  it('produces a stable date-stamped title', () => {
    const title = defaultSessionTitle(Date.UTC(2026, 0, 15, 10, 0, 0));
    expect(title).toMatch(/^Untitled session — \d{4}-\d{2}-\d{2}$/);
  });
});

describe('formatSessionMarkdown', () => {
  it('emits the header, summary, suggestions, and transcript sections', () => {
    const md = formatSessionMarkdown(
      sample({
        summary: {
          body: '- Ship cloud beta on Friday\n- Owners: alice, bob',
          providerId: LlmProviderId.Anthropic,
          model: 'claude-3-5-haiku-latest',
          generatedAt: Date.UTC(2026, 5, 10, 9, 30, 5),
        },
      }),
    );
    expect(md).toContain('# Q3 planning sync');
    expect(md).toContain('- Source: Google Meet — Engineering');
    expect(md).toContain('## Summary');
    expect(md).toContain('- Ship cloud beta on Friday');
    expect(md).toContain('_Generated by anthropic (claude-3-5-haiku-latest)');
    expect(md).toContain('## Assist suggestions');
    expect(md).toContain('Propose a Friday cutoff');
    expect(md).toContain('## Transcript');
    expect(md).toContain('we should ship the cloud beta this week');
  });

  it('omits sections that have no content', () => {
    const md = formatSessionMarkdown(
      sample({ suggestions: [], transcript: [], summary: null }),
    );
    expect(md).not.toContain('## Summary');
    expect(md).not.toContain('## Assist suggestions');
    expect(md).not.toContain('## Transcript');
  });

  it('collapses whitespace inside suggestion lines so the output is clean', () => {
    const md = formatSessionMarkdown(
      sample({
        suggestions: [
          {
            id: 1,
            triggeredAt: Date.UTC(2026, 5, 10, 9, 2, 0),
            completedAt: null,
            text: '  hello \n\n  world  ',
            streaming: false,
            providerId: LlmProviderId.OpenAI,
            ttsAvailable: false,
          },
        ],
        transcript: [],
        summary: null,
      }),
    );
    expect(md).toContain('hello world');
    expect(md).not.toContain('hello \n\n  world');
  });
});
